import { Ionicons } from "@expo/vector-icons";
import { router, useFocusEffect } from "expo-router";
import { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Modal, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useAuth } from "../../context/AuthContext";
import { createSellerReview, getMyOrders, getMyReviews, Order, SellerReview } from "../../services/api";

const CARDINAL = "#A6192E"; const BG = "#F7F7F8"; const TEXT = "#171717"; const MUTED = "#737373"; const BORDER = "#E7E7E8";
function storeName(order: Order) { return typeof order.store === "object" ? order.store.name : "Campus Store"; }

export default function ReviewsScreen() {
  const { token } = useAuth();
  const [orders, setOrders] = useState<Order[]>([]); const [reviews, setReviews] = useState<SellerReview[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [selected, setSelected] = useState<Order | null>(null); const [rating, setRating] = useState(0); const [comment, setComment] = useState(""); const [submitting, setSubmitting] = useState(false);
  const load = useCallback(async (refresh = false) => { if (!token) return; try { refresh ? setRefreshing(true) : setLoading(true); const [allOrders, myReviews] = await Promise.all([getMyOrders(token), getMyReviews(token)]); setOrders(allOrders.filter((order) => order.status === "Completed")); setReviews(myReviews); } catch (error) { Alert.alert("Reviews", error instanceof Error ? error.message : "Unable to load reviews."); } finally { setLoading(false); setRefreshing(false); } }, [token]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const reviewedOrderIds = useMemo(() => new Set(reviews.map((review) => String(review.order))), [reviews]);
  const submit = async () => { if (!selected || !token) return; if (!rating) return Alert.alert("Star rating required", "Choose from 1 to 5 stars."); if (comment.trim().length < 3) return Alert.alert("Comment required", "Write at least 3 characters about your experience."); try { setSubmitting(true); await createSellerReview(token, selected._id, rating, comment.trim()); setSelected(null); setRating(0); setComment(""); await load(true); Alert.alert("Thank you!", "Your review has been posted."); } catch (error) { Alert.alert("Review not submitted", error instanceof Error ? error.message : "Please try again."); } finally { setSubmitting(false); } };
  if (loading) return <SafeAreaView style={styles.safe}><View style={styles.center}><ActivityIndicator color={CARDINAL} size="large" /><Text style={styles.muted}>Loading reviews…</Text></View></SafeAreaView>;
  return <SafeAreaView style={styles.safe} edges={["top"]}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} tintColor={CARDINAL} />}><View style={styles.header}><View><Text style={styles.eyebrow}>ORDER HISTORY</Text><Text style={styles.title}>Rate Sellers</Text><Text style={styles.subtitle}>Share a star rating and a comment after a completed order.</Text></View><Pressable onPress={() => router.back()} style={styles.close}><Ionicons name="close" size={21} color={TEXT} /></Pressable></View>{orders.length === 0 ? <View style={styles.empty}><Ionicons name="star-outline" size={44} color={CARDINAL} /><Text style={styles.emptyTitle}>No completed orders</Text><Text style={styles.emptyText}>After you pick up a completed order, you can review its seller here.</Text></View> : orders.map((order) => { const reviewed = reviewedOrderIds.has(order._id); return <View key={order._id} style={styles.card}><View style={styles.icon}><Ionicons name="storefront-outline" size={21} color={CARDINAL} /></View><View style={styles.cardText}><Text style={styles.store}>{storeName(order)}</Text><Text style={styles.order}>Order #{order._id.slice(-6).toUpperCase()}</Text></View>{reviewed ? <View style={styles.done}><Ionicons name="checkmark" size={14} color="#28794D" /><Text style={styles.doneText}>Reviewed</Text></View> : <Pressable onPress={() => setSelected(order)} style={styles.rate}><Text style={styles.rateText}>Rate</Text><Ionicons name="star" size={14} color="#fff" /></Pressable>}</View>; })}</ScrollView><Modal transparent animationType="fade" visible={!!selected} onRequestClose={() => setSelected(null)}><View style={styles.overlay}><View style={styles.modal}><Text style={styles.modalTitle}>Rate {selected ? storeName(selected) : "seller"}</Text><Text style={styles.modalSub}>Your feedback is visible to the seller.</Text><View style={styles.stars}>{[1,2,3,4,5].map((star) => <Pressable key={star} onPress={() => setRating(star)} hitSlop={7}><Ionicons name={star <= rating ? "star" : "star-outline"} size={34} color={star <= rating ? "#E7A400" : "#B7B7B7"} /></Pressable>)}</View><TextInput value={comment} onChangeText={setComment} multiline maxLength={1000} placeholder="Write your comment…" placeholderTextColor="#999" style={styles.comment} /><View style={styles.actions}><Pressable onPress={() => setSelected(null)} style={styles.cancel}><Text style={styles.cancelText}>Cancel</Text></Pressable><Pressable disabled={submitting} onPress={submit} style={[styles.submit, submitting && { opacity: 0.6 }]}>{submitting ? <ActivityIndicator color="#fff" /> : <Text style={styles.submitText}>Post Review</Text>}</Pressable></View></View></View></Modal></SafeAreaView>;
}

const styles = StyleSheet.create({ safe:{flex:1,backgroundColor:BG}, center:{flex:1,alignItems:"center",justifyContent:"center",gap:12}, muted:{color:MUTED}, content:{padding:18,paddingBottom:30}, header:{flexDirection:"row",justifyContent:"space-between",marginBottom:22}, eyebrow:{fontSize:10,fontWeight:"900",letterSpacing:1.2,color:CARDINAL}, title:{fontSize:27,fontWeight:"900",color:TEXT,marginTop:4}, subtitle:{color:MUTED,fontSize:12,lineHeight:18,marginTop:5,maxWidth:270}, close:{width:39,height:39,borderRadius:12,alignItems:"center",justifyContent:"center",backgroundColor:"#fff",borderWidth:1,borderColor:BORDER}, card:{minHeight:80,backgroundColor:"#fff",borderWidth:1,borderColor:BORDER,borderRadius:17,padding:13,flexDirection:"row",alignItems:"center",marginBottom:10}, icon:{width:43,height:43,borderRadius:13,backgroundColor:"#FBECEF",alignItems:"center",justifyContent:"center"}, cardText:{flex:1,marginLeft:10}, store:{fontWeight:"900",fontSize:13,color:TEXT}, order:{fontSize:10,color:MUTED,marginTop:4}, rate:{backgroundColor:CARDINAL,borderRadius:10,paddingHorizontal:12,height:34,flexDirection:"row",gap:5,alignItems:"center",justifyContent:"center"}, rateText:{color:"#fff",fontSize:11,fontWeight:"900"}, done:{backgroundColor:"#EAF7EE",borderRadius:10,paddingHorizontal:10,height:32,flexDirection:"row",gap:4,alignItems:"center"}, doneText:{fontSize:10,fontWeight:"800",color:"#28794D"}, empty:{marginTop:70,alignItems:"center",padding:30}, emptyTitle:{color:TEXT,fontSize:17,fontWeight:"900",marginTop:12}, emptyText:{color:MUTED,textAlign:"center",fontSize:12,lineHeight:18,marginTop:5}, overlay:{flex:1,backgroundColor:"#00000070",justifyContent:"center",padding:20}, modal:{backgroundColor:"#fff",borderRadius:22,padding:20}, modalTitle:{fontSize:19,fontWeight:"900",color:TEXT}, modalSub:{fontSize:12,color:MUTED,marginTop:4}, stars:{flexDirection:"row",justifyContent:"space-between",marginVertical:18,paddingHorizontal:3}, comment:{borderWidth:1,borderColor:BORDER,borderRadius:14,minHeight:105,textAlignVertical:"top",padding:12,fontSize:13,color:TEXT}, actions:{flexDirection:"row",justifyContent:"flex-end",gap:9,marginTop:15}, cancel:{height:42,paddingHorizontal:15,justifyContent:"center"}, cancelText:{color:MUTED,fontWeight:"800"}, submit:{height:42,paddingHorizontal:17,borderRadius:11,backgroundColor:CARDINAL,justifyContent:"center"}, submitText:{color:"#fff",fontSize:12,fontWeight:"900"} });
