import { Ionicons } from "@expo/vector-icons";
import { useCallback, useState } from "react";
import { useFocusEffect } from "expo-router";
import { ActivityIndicator, Alert, Modal, Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { useAuth } from "../../context/AuthContext";
import { createAdminVoucher, getAdminVouchers, updateAdminVoucher, Voucher } from "../../services/api";

const RED = "#A6192E", GOLD = "#D8B56A", TEXT = "#171717", MUTED = "#737373", BORDER = "#E7E7E8", BG = "#F7F7F8", WHITE = "#FFFFFF";

export default function AdminVouchers() {
  const { token } = useAuth(); const [vouchers, setVouchers] = useState<Voucher[]>([]); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false);
  const [code, setCode] = useState(""); const [title, setTitle] = useState(""); const [percent, setPercent] = useState("5"); const [minimum, setMinimum] = useState("0"); const [newOnly, setNewOnly] = useState(true);
  const load = useCallback(async () => { if (!token) return; try { setLoading(true); setVouchers(await getAdminVouchers(token)); } catch (e) { Alert.alert("Vouchers", e instanceof Error ? e.message : "Unable to load vouchers."); } finally { setLoading(false); } }, [token]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const create = async () => { if (!token) return; try { setSaving(true); const voucher = await createAdminVoucher(token, { code, title, discountPercent: Number(percent), minimumOrder: Number(minimum), newUsersOnly: newOnly }); setVouchers((list) => [voucher, ...list]); setOpen(false); setCode(""); setTitle(""); setPercent("5"); setMinimum("0"); setNewOnly(true); } catch (e) { Alert.alert("Create Voucher", e instanceof Error ? e.message : "Unable to create voucher."); } finally { setSaving(false); } };
  const toggle = async (voucher: Voucher) => { if (!token) return; try { const updated = await updateAdminVoucher(token, voucher._id, { active: !voucher.active }); setVouchers((list) => list.map((item) => item._id === updated._id ? updated : item)); } catch (e) { Alert.alert("Voucher", e instanceof Error ? e.message : "Unable to update voucher."); } };
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.header}><View><Text style={s.eyebrow}>MASTER ADMIN</Text><Text style={s.title}>Vouchers</Text><Text style={s.subtitle}>Create promotions sellers can enable for their products.</Text></View><Pressable style={s.add} onPress={() => setOpen(true)}><Ionicons name="add" size={24} color={WHITE} /></Pressable></View>{loading ? <ActivityIndicator size="large" color={RED} style={s.loading} /> : vouchers.length ? vouchers.map((v) => <View key={v._id} style={[s.card, !v.active && s.inactive]}><View style={s.cardTop}><View style={s.icon}><Ionicons name="ticket-outline" size={21} color={RED} /></View><Switch value={v.active} onValueChange={() => void toggle(v)} trackColor={{ false: "#D5D5D5", true: "#E9B7C0" }} thumbColor={v.active ? RED : "#FFFFFF"} /></View><Text style={s.code}>{v.code}</Text><Text style={s.cardTitle}>{v.title}</Text><Text style={s.detail}>{v.discountPercent}% off{v.minimumOrder ? ` · min. ₱${v.minimumOrder}` : ""}</Text><Text style={s.detail}>{v.newUsersOnly ? "New users only" : "All eligible customers"}</Text></View>) : <View style={s.empty}><Ionicons name="ticket-outline" size={38} color={MUTED}/><Text style={s.emptyTitle}>No vouchers yet</Text><Text style={s.emptyText}>Create a platform voucher, then sellers can choose where to enable it.</Text></View>}</ScrollView><Modal visible={open} transparent animationType="slide" onRequestClose={() => setOpen(false)}><View style={s.modalRoot}><Pressable style={s.backdrop} onPress={() => setOpen(false)}/><View style={s.sheet}><Text style={s.sheetTitle}>Create Voucher</Text><Field label="Voucher Code" value={code} onChangeText={(value) => setCode(value.toUpperCase())} placeholder="NEWUSER5"/><Field label="Voucher Title" value={title} onChangeText={setTitle} placeholder="5% Off for New Users"/><View style={s.row}><View style={s.half}><Field label="Discount %" value={percent} onChangeText={setPercent} keyboardType="decimal-pad" placeholder="5"/></View><View style={s.half}><Field label="Min. Order" value={minimum} onChangeText={setMinimum} keyboardType="decimal-pad" placeholder="0"/></View></View><View style={s.switchRow}><View><Text style={s.switchTitle}>New users only</Text><Text style={s.switchSub}>Customer must not have a prior order.</Text></View><Switch value={newOnly} onValueChange={setNewOnly} trackColor={{ false: "#D5D5D5", true: "#E9B7C0" }} thumbColor={newOnly ? RED : WHITE}/></View><Pressable disabled={saving} style={s.create} onPress={() => void create()}>{saving ? <ActivityIndicator color={WHITE}/> : <Text style={s.createText}>Create Voucher</Text>}</Pressable></View></View></Modal></SafeAreaView>;
}
function Field({ label, ...props }: { label: string } & React.ComponentProps<typeof TextInput>) { return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput style={s.input} placeholderTextColor="#9A9A9A" {...props}/></View>; }
const s = StyleSheet.create({ safe:{flex:1,backgroundColor:BG},content:{padding:20,paddingBottom:32},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"flex-start",marginBottom:20},eyebrow:{fontSize:10,fontWeight:"800",letterSpacing:1.4,color:GOLD},title:{fontSize:28,fontWeight:"900",color:TEXT,marginTop:4},subtitle:{color:MUTED,fontSize:12,marginTop:4,maxWidth:265,lineHeight:18},add:{width:46,height:46,borderRadius:15,backgroundColor:RED,alignItems:"center",justifyContent:"center"},loading:{marginTop:70},card:{backgroundColor:WHITE,borderWidth:1,borderColor:BORDER,borderRadius:18,padding:15,marginBottom:11},inactive:{opacity:.55},cardTop:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},icon:{width:40,height:40,borderRadius:13,backgroundColor:"#F8E9EC",alignItems:"center",justifyContent:"center"},code:{marginTop:13,color:RED,fontWeight:"900",letterSpacing:1,fontSize:13},cardTitle:{marginTop:3,fontSize:16,fontWeight:"900",color:TEXT},detail:{marginTop:4,fontSize:11,color:MUTED},empty:{paddingTop:80,alignItems:"center",paddingHorizontal:35},emptyTitle:{fontSize:17,fontWeight:"900",color:TEXT,marginTop:12},emptyText:{fontSize:12,color:MUTED,textAlign:"center",lineHeight:18,marginTop:6},modalRoot:{flex:1,justifyContent:"flex-end"},backdrop:{...StyleSheet.absoluteFill,backgroundColor:"rgba(0,0,0,.45)"},sheet:{backgroundColor:WHITE,borderTopLeftRadius:26,borderTopRightRadius:26,padding:20,paddingBottom:32},sheetTitle:{fontSize:20,fontWeight:"900",color:TEXT,marginBottom:12},field:{marginTop:11},label:{fontSize:11,fontWeight:"800",color:TEXT,marginBottom:6},input:{height:47,borderWidth:1,borderColor:BORDER,borderRadius:13,paddingHorizontal:13,color:TEXT,fontSize:14},row:{flexDirection:"row",gap:10},half:{flex:1},switchRow:{marginTop:18,padding:13,borderRadius:14,backgroundColor:"#F8F8F9",flexDirection:"row",justifyContent:"space-between",alignItems:"center"},switchTitle:{fontSize:13,fontWeight:"800",color:TEXT},switchSub:{fontSize:10,color:MUTED,marginTop:2},create:{height:52,borderRadius:15,backgroundColor:RED,alignItems:"center",justifyContent:"center",marginTop:18},createText:{color:WHITE,fontSize:14,fontWeight:"900"} });
