import { Ionicons } from "@expo/vector-icons";
import { router, useFocusEffect } from "expo-router";
import { useCallback, useState } from "react";
import { ActivityIndicator, Alert, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useAuth } from "../../context/AuthContext";
import { getSellerReviews, SellerReview } from "../../services/api";

const CARDINAL = "#A6192E"; const TEXT = "#171717"; const MUTED = "#737373"; const BORDER = "#E7E7E8";
export default function SellerReviews() {
  const { token } = useAuth(); const [reviews, setReviews] = useState<SellerReview[]>([]); const [average, setAverage] = useState(0); const [count, setCount] = useState(0); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async (refresh = false) => { if (!token) return; try { refresh ? setRefreshing(true) : setLoading(true); const data = await getSellerReviews(token); setReviews(data.reviews); setAverage(data.averageRating); setCount(data.reviewCount); } catch (error) { Alert.alert("Reviews", error instanceof Error ? error.message : "Unable to load seller reviews."); } finally { setLoading(false); setRefreshing(false); } }, [token]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  if (loading) return <SafeAreaView style={styles.safe}><View style={styles.center}><ActivityIndicator color={CARDINAL} size="large" /><Text style={styles.muted}>Loading feedback…</Text></View></SafeAreaView>;
  return <SafeAreaView style={styles.safe} edges={["top"]}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} tintColor={CARDINAL} />}><View style={styles.header}><View><Text style={styles.eyebrow}>SELLER CENTER</Text><Text style={styles.title}>Customer Reviews</Text><Text style={styles.subtitle}>Feedback from completed customer orders.</Text></View><Ionicons name="star" size={25} color="#D59B00" /></View><View style={styles.summary}><View><Text style={styles.average}>{average ? average.toFixed(1) : "—"}</Text><Text style={styles.summaryLabel}>Average rating</Text></View><View style={styles.bigStar}><Ionicons name="star" size={33} color="#fff" /></View><View><Text style={styles.count}>{count}</Text><Text style={styles.summaryLabel}>Reviews</Text></View></View>{reviews.length ? reviews.map((review) => <View key={review._id} style={styles.card}><View style={styles.cardTop}><Text style={styles.name}>{`${review.client?.firstName ?? "Customer"} ${review.client?.lastName ?? ""}`.trim()}</Text><View style={styles.rating}>{[1,2,3,4,5].map((star) => <Ionicons key={star} name={star <= review.rating ? "star" : "star-outline"} size={14} color="#D59B00" />)}</View></View><Text style={styles.comment}>{review.comment}</Text><Text style={styles.date}>{new Date(review.createdAt).toLocaleDateString("en-PH", { month:"short", day:"numeric", year:"numeric" })}</Text></View>) : <View style={styles.empty}><Ionicons name="star-outline" size={45} color={CARDINAL} /><Text style={styles.emptyTitle}>No reviews yet</Text><Text style={styles.emptyText}>Completed-order reviews from clients will appear here.</Text></View>}</ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:"#F7F7F8"},center:{flex:1,alignItems:"center",justifyContent:"center",gap:12},muted:{color:MUTED},content:{padding:18,paddingBottom:30},header:{flexDirection:"row",justifyContent:"space-between",marginBottom:18},eyebrow:{fontSize:10,fontWeight:"900",color:CARDINAL,letterSpacing:1.2},title:{fontSize:26,fontWeight:"900",color:TEXT,marginTop:4},subtitle:{fontSize:12,color:MUTED,marginTop:5},summary:{minHeight:105,backgroundColor:CARDINAL,borderRadius:19,padding:18,flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:18},average:{color:"#fff",fontSize:29,fontWeight:"900"},count:{color:"#fff",fontSize:29,fontWeight:"900",textAlign:"right"},summaryLabel:{color:"#F6DCE1",fontSize:10,fontWeight:"700",marginTop:2},bigStar:{width:53,height:53,borderRadius:17,alignItems:"center",justifyContent:"center",backgroundColor:"#FFFFFF25"},card:{backgroundColor:"#fff",borderRadius:17,borderWidth:1,borderColor:BORDER,padding:15,marginBottom:10},cardTop:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},name:{color:TEXT,fontSize:13,fontWeight:"900"},rating:{flexDirection:"row",gap:2},comment:{marginTop:9,color:TEXT,fontSize:12,lineHeight:18},date:{marginTop:10,color:MUTED,fontSize:10,fontWeight:"700"},empty:{marginTop:65,alignItems:"center",padding:25},emptyTitle:{marginTop:12,color:TEXT,fontWeight:"900",fontSize:16},emptyText:{marginTop:5,color:MUTED,textAlign:"center",fontSize:12}});
