import { Ionicons } from "@expo/vector-icons";
import { useCallback, useState } from "react";
import { useFocusEffect } from "expo-router";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { useAuth } from "../../context/AuthContext";
import { LIGHT_COLORS, type AppColors, useAppTheme } from "../../context/ThemeContext";
import { createThemedStyleSheet } from "../../utils/themeStyles";
import { getSellerVouchers, Product, saveSellerVoucherActivation, Voucher, VoucherActivation } from "../../services/api";

const RED="#A6192E", GOLD="#D8B56A", TEXT="#171717", MUTED="#737373", BG="#F7F7F8", WHITE="#FFFFFF", BORDER="#E7E7E8";
export default function SellerVouchers() {
  const { colors } = useAppTheme(); s = createStyles(colors);
 const { token }=useAuth(); const [vouchers,setVouchers]=useState<Voucher[]>([]); const [activations,setActivations]=useState<VoucherActivation[]>([]); const [products,setProducts]=useState<Product[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState<string | null>(null);
 const load=useCallback(async()=>{if(!token)return;try{setLoading(true);const data=await getSellerVouchers(token);setVouchers(data.vouchers);setActivations(data.activations);setProducts(data.products);}catch(e){Alert.alert("Vouchers",e instanceof Error?e.message:"Unable to load vouchers.");}finally{setLoading(false);}},[token]); useFocusEffect(useCallback(()=>{void load();},[load]));
 const toggle=async(v:Voucher)=>{if(!token)return;const current=activations.find(a=>String(a.voucher)===v._id);try{setSaving(v._id);const activation=await saveSellerVoucherActivation(token,v._id,!current?.enabled,current?.productIds??[]);setActivations(list=>[...list.filter(a=>String(a.voucher)!==v._id),activation]);}catch(e){Alert.alert("Voucher",e instanceof Error?e.message:"Unable to update voucher.");}finally{setSaving(null);}};
 const selectProducts=(v:Voucher)=>{const current=activations.find(a=>String(a.voucher)===v._id);const selected=new Set(current?.productIds??[]);Alert.alert("Eligible Products", "Selected products can use this voucher. Leaving all unselected means every product in your store.", [{text:"All Store Products",onPress:()=>void save(v, current?.enabled??true,[])},...products.map(p=>({text:`${selected.has(p._id)?"✓ ":""}${p.name}`,onPress:()=>{selected.has(p._id)?selected.delete(p._id):selected.add(p._id);selectProductsWith(v,[...selected],current?.enabled??true);}})),{text:"Cancel",style:"cancel"}]);};
 const selectProductsWith=(v:Voucher, ids:string[], enabled:boolean)=>Alert.alert("Product Selection",`${ids.length} product${ids.length===1?"":"s"} selected. Save this selection?`,[{text:"Cancel",style:"cancel"},{text:"Save",onPress:()=>void save(v,enabled,ids)}]);
 const save=async(v:Voucher,enabled:boolean,ids:string[])=>{if(!token)return;try{setSaving(v._id);const activation=await saveSellerVoucherActivation(token,v._id,enabled,ids);setActivations(list=>[...list.filter(a=>String(a.voucher)!==v._id),activation]);}catch(e){Alert.alert("Voucher",e instanceof Error?e.message:"Unable to save voucher.");}finally{setSaving(null);}};
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>SELLER TOOLS</Text><Text style={s.title}>Vouchers</Text><Text style={s.subtitle}>Enable admin vouchers only for products in your own store.</Text>{loading?<ActivityIndicator color={RED} size="large" style={s.loading}/>:vouchers.length?vouchers.map(v=>{const a=activations.find(x=>String(x.voucher)===v._id);return <View style={s.card} key={v._id}><View style={s.top}><View style={s.icon}><Ionicons name="ticket-outline" size={21} color={RED}/></View><Switch value={Boolean(a?.enabled)} disabled={saving===v._id} onValueChange={()=>void toggle(v)} trackColor={{false:"#D6D6D6",true:"#E9B7C0"}} thumbColor={a?.enabled?RED:WHITE}/></View><Text style={s.code}>{v.code}</Text><Text style={s.name}>{v.title}</Text><Text style={s.detail}>{v.discountPercent}% off{v.minimumOrder?` · ₱${v.minimumOrder} minimum`:""}</Text><Text style={s.detail}>{a?.productIds?.length?`${a.productIds.length} selected product(s)`:"All store products"}</Text><Pressable style={s.select} onPress={()=>selectProducts(v)}><Ionicons name="fast-food-outline" size={16} color={RED}/><Text style={s.selectText}>Choose eligible products</Text></Pressable></View>}):<View style={s.empty}><Ionicons name="ticket-outline" size={38} color={MUTED}/><Text style={s.emptyText}>No active vouchers from the admin yet.</Text></View>}</ScrollView></SafeAreaView>;
}
const createStyles = (colors: AppColors) => createThemedStyleSheet(colors, {safe:{flex:1,backgroundColor:BG},content:{padding:20,paddingBottom:32},eyebrow:{fontSize:10,fontWeight:"800",color:GOLD,letterSpacing:1.4},title:{fontSize:28,fontWeight:"900",color:TEXT,marginTop:4},subtitle:{fontSize:12,color:MUTED,marginTop:4,lineHeight:18},loading:{marginTop:70},card:{marginTop:15,backgroundColor:WHITE,borderWidth:1,borderColor:BORDER,borderRadius:18,padding:15},top:{flexDirection:"row",justifyContent:"space-between"},icon:{width:40,height:40,borderRadius:13,backgroundColor:"#F8E9EC",alignItems:"center",justifyContent:"center"},code:{marginTop:12,color:RED,fontSize:13,fontWeight:"900",letterSpacing:1},name:{fontSize:16,fontWeight:"900",color:TEXT,marginTop:3},detail:{fontSize:11,color:MUTED,marginTop:4},select:{height:42,borderRadius:12,backgroundColor:"#F9EFF1",marginTop:13,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:7},selectText:{fontSize:12,fontWeight:"800",color:RED},empty:{alignItems:"center",paddingTop:75},emptyText:{color:MUTED,fontSize:12,marginTop:12,textAlign:"center"}});
let s = createStyles(LIGHT_COLORS);
